@startuml
package Corporations {
    object Client
    object Consultant
    object GeneralContractor
    object SubContractor
}
package Contracts {
    object Project
    object Contract
    object SubContract
}
object CertificateOfCompletion
object CertificateOfPayment
package Payments {
    object ContractPayment
    object SubContractPayment
}

object ClientProjectRelationship
object ConsultantProjectRelationship
object ContractorContractRelationship
object ContractSubContractRelationship
object SubContractorSubContractRelationship

Client --> Project
(Client, Project) .. ClientProjectRelationship
Consultant --> Project
(Consultant, Project) .. ConsultantProjectRelationship
Project --> Contract
GeneralContractor --> Contract
(GeneralContractor, Contract) .. ContractorContractRelationship
Contract --> SubContract
(Contract, SubContract) .. ContractSubContractRelationship
SubContractor --> SubContract
(SubContractor, SubContract) .. SubContractorSubContractRelationship
Contract --> ContractPayment
SubContract --> CertificateOfCompletion
CertificateOfCompletion --> CertificateOfPayment
CertificateOfPayment --> SubContractPayment
@enduml
